### ISSUE TITLE
Arrays of enum values

### ISSUE THREAD

**Issue by arkraft** [Manweill/swagger-axios-codegen#29]
I have a swagger configuration where one attribute is an array of enum values (number). This enum is correctly translated into a type, but the property itself is not an array anymore. For example:

```yaml
 features:
        type: array
        uniqueItems: true
        items:
          type: number
          enum:
            - 10
            - 11
            - 20
            - 30
            - 40
            - 50
            - 51
            - 61
            - 71
            - 72
```

creates the following enum type:
```typescript
type StructureDtoFeatures = 10 | 11 | 20 | 30 | 40 | 50 | 51 | 61 | 71 | 72;
```
but the property itself is this:
```typescript
...
  features: StructureDtoFeatures;
...
```
which is not an array.

This part works fine in the Swagger Editor and when creating a client with `typescript-angular`, the Class is also correct. 

```typescript
...
    features?: Array<number>;
...
```
